app:
  port: 3000
  session:
    host: "localhost"
    port: 6379
    cleanup_time: 7200000
    cleanup_interval: 3600000
  global_request_timeout: 5000
  global_session_timeout: 3600000
log:
  customlevels:
    ERROR: 1
    INFO: 1
    LOG: 1
    WARN: 1
apis:
  base: "/apis"
  health: "/service/healthcheck"
  releases:
    train:
      stable: "0.0.0"
      beta: "0.0.0"
      alpha: "0.0.0"
    bus:
      stable: "0.1.0"
      beta: "0.1.0"
      alpha: "0.1.0"
